### ISSUE TITLE
Outdated @expo/config-plugins

### ISSUE THREAD

**Issue by tom-at-pixel** [morrowdigital/watermelondb-expo-plugin#18]
This plugin is using `@expo/config-plugins` version `^5.0.4`, while Expo 48 uses `6.0.0`. (And `7.0.0` is about to become stable.)

This is nothing too bad, but it keeps tripping up expo doctor:

```
Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
```

It would also keep this package up to date as WatermelonDB and Expo are evolving.

**Comment by brunokiafuka** [comment]
Hi @tom-at-pixel please install `"@morrowdigital/watermelondb-expo-plugin": "^2.1.2",`. Let us know if this helps. 

Feel free to push a PR and reopen this issue if the issue persists. 

<img src="https://media2.giphy.com/media/3o6ozm2sJ102JdumVq/giphy.gif"/>
