### ISSUE TITLE
Errors with WatermelonDB 0.26

### ISSUE THREAD

**Issue by itsdaveit** [morrowdigital/watermelondb-expo-plugin#23]
Seems like its not possible to use this with current WatermelonDB version 0.26.
See this Discussion:
https://github.com/Nozbe/WatermelonDB/issues/1592

**Comment by killerchip** [comment]
Hello. You need to build an expo dev-client, or update SDK to latest (49.0.11), which allows `npx expo run:xxx` to build automatically an custom dev-client.
