### ISSUE TITLE
Setting up the plugin

### ISSUE THREAD

**Issue by tndungu** [morrowdigital/watermelondb-expo-plugin#3]
I'm using Expo for react native app, after npm install how do I setup a simple project?

**Comment by brunokiafuka** [comment]
> I'm using Expo for react native app, after npm install how do I setup a simple project?

Hi @tndungu, to set up the plugin you will have to: 
- Add the [plugins array on your `app.json`](https://docs.expo.dev/guides/config-plugins/#using-a-plugin-in-your-app) file and include the plugin reference to it,
```json
{
  "plugins": ["@morrowdigital/watermelondb-expo-plugin"]
}
```
- Run [`expo prebuild`](https://docs.expo.dev/workflow/expo-cli/#eject) on your terminal 
- Then finally add run `expo run:[ios|android]` 

> If you are using Expo SDK 44 for ios you will need to patch the watermelon package as shown [here](https://github.com/Nozbe/WatermelonDB/pull/1249/)
