### ISSUE TITLE
Not working with Expo SDK 46

### ISSUE THREAD

**Issue by daviddunnington** [morrowdigital/watermelondb-expo-plugin#6]
When trying to build the app after installing the plugin I get the below error. Can you help resolve this issue? 

(/Users/daviddunnington/Development/apps/my-app/ios/Pods/Target Support Files/Pods-myapp/ExpoModulesProvider.swift:11:8)

   9 | import ExpoKeepAwake
  10 | #if EXPO_CONFIGURATION_DEBUG
  11 | import EXDevLauncher |        
                     ^ no such module 'EXDevLauncher'
  12 | import EXDevMenu
  13 | #endif
  14 |

**Comment by sainijagjit** [comment]
Is there any update on this ?

**Comment by ChrisSimoniMBT** [comment]
@sainijagjit @daviddunnington Refer to this for a possible solution. https://github.com/expo/expo/issues/18784#issuecomment-1332764301

**Comment by Foosballfan** [comment]
Tracked in #7
