### ISSUE TITLE
[Bug] Compatibility update for Expo SDK 46+

### ISSUE THREAD

**Issue by ChronSyn** [morrowdigital/watermelondb-expo-plugin#7]
**Issue**
There have been a number of reports that the WatermelonDB config plugin is not working correctly with Expo SDK 46+.

**Related issues:**
#5 #6 

**Further notes**
The plugin hasn't been updated since December 2021 and makes use of node internal imports such as `fs` and `path`.
With that in mind, it's a good time to consider updating the code to use functions which are specifically designed for config plugin development.

**Comment by Foosballfan** [comment]
@ChronSyn  fixed in https://github.com/morrowdigital/watermelondb-expo-plugin/pull/8 
Please will you test and publish to NPM?

**Comment by brunokiafuka** [comment]
#9 fixes this issue.
